### ISSUE TITLE
Keyerror occurs when implement douban dataset

### ISSUE THREAD

**Issue by jindeok** [deepopo/CENALP#2]
![image](https://user-images.githubusercontent.com/35905280/99880227-8a5b1780-2c55-11eb-81c3-d6ccf18cf9d0.png)

Hello,
Really appreciate for providing source code for the paper. 
However,
When I try to implement CENALP algorithm for 'Douban dataset', the above Key error occurs.
other dataset such as bigtoy or facebook-twitter dataset works well without any error occursion.

Can I know what would be the problem??

**Comment by deepopo** [comment]
Sorry, I just saw this issue. It seems that there's something wrong with the alignment dictionary when I clean up the code. The reason for the error is that there exist many edges in G1 which G2 doesn't have. 

The code has been revised.

Thanks for your attention.

**Comment by bobo1270** [comment]
But now there is still this problem 
![image](https://github.com/deepopo/CENALP/assets/106292976/387fe12c-4f3f-432c-a6ab-81aeafea6ed3)

**Comment by deepopo** [comment]
Is it line 341 in CENALP.py? It seems that I have already commented out this line of code.

**Comment by bobo1270** [comment]
yes, line341 you have commented out.
but my error is line 152, there is the same code.

**Comment by deepopo** [comment]
> yes, line341 you have commented out. but my error is line 152, there is the same code.

Thanks for pointing it out. I have updated the corresponding code.

**Comment by bobo1270** [comment]
Thank you, the modified code has no problems on the three data sets. 

I appreciate the work you have done. I recently want to do in-depth research based on your work. 
If I have any questions in the future, I hope to have the opportunity to ask you for advice. 

Good luck with your work
